ALTER TABLE public.scraped_phones
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS first_seen TIMESTAMPTZ DEFAULT NOW();
