// Cities by country for regional filtering
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  // Netherlands
  Netherlands: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
    'Haarlem',
    'Arnhem',
    'Maastricht',
    'Leiden',
    'Dordrecht',
  ],
  // Germany
  Germany: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
  ],
  // Czech Republic
  'Czech Republic': [
    'Prague',
    'Brno',
    'Ostrava',
    'Pilsen',
    'Liberec',
    'Olomouc',
    'České Budějovice',
    'Hradec Králové',
    'Pardubice',
    'Zlín',
  ],
  // Switzerland
  Switzerland: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Winterthur',
    'Lucerne',
    'St. Gallen',
    'Lugano',
    'Biel',
  ],
  // Spain
  Spain: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
  ],
  // France
  France: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
  ],
  // Denmark
  Denmark: [
    'Copenhagen',
    'Aarhus',
    'Odense',
    'Aalborg',
    'Esbjerg',
    'Randers',
    'Kolding',
    'Horsens',
    'Vejle',
    'Roskilde',
  ],
  // Poland
  Poland: [
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
  ],
  // Italy
  Italy: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Catania',
    'Venice',
  ],
  // Portugal
  Portugal: [
    'Lisbon',
    'Porto',
    'Amadora',
    'Braga',
    'Funchal',
    'Coimbra',
    'Setúbal',
    'Almada',
    'Aveiro',
    'Faro',
  ],
  // Sweden
  Sweden: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
  ],
  // Norway
  Norway: [
    'Oslo',
    'Bergen',
    'Trondheim',
    'Stavanger',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Sandnes',
    'Tromsø',
    'Sarpsborg',
  ],
  // Colombia
  Colombia: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Ibagué',
  ],
  // Canada
  Canada: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
  ],
}

// Get cities for a country
export function getCitiesForCountry(countryName: string): string[] {
  return CITIES_BY_COUNTRY[countryName] || []
}
