export interface Country {
  code: string
  name: string
  flag: string
  region: string
}

export const SUPPORTED_COUNTRIES: Country[] = [
  // Europe
  { code: "al", name: "Albania", flag: "🇦🇱", region: "Europe" },
  { code: "ad", name: "Andorra", flag: "🇦🇩", region: "Europe" },
  { code: "am", name: "Armenia", flag: "🇦🇲", region: "Europe" },
  { code: "at", name: "Austria", flag: "🇦🇹", region: "Europe" },
  { code: "by", name: "Belarus", flag: "🇧🇾", region: "Europe" },
  { code: "be", name: "Belgium", flag: "🇧🇪", region: "Europe" },
  { code: "ba", name: "Bosnia and Herzegovina", flag: "🇧🇦", region: "Europe" },
  { code: "bg", name: "Bulgaria", flag: "🇧🇬", region: "Europe" },
  { code: "hr", name: "Croatia", flag: "🇭🇷", region: "Europe" },
  { code: "cy", name: "Cyprus", flag: "🇨🇾", region: "Europe" },
  { code: "cz", name: "Czech Republic", flag: "🇨🇿", region: "Europe" },
  { code: "dk", name: "Denmark", flag: "🇩🇰", region: "Europe" },
  { code: "ee", name: "Estonia", flag: "🇪🇪", region: "Europe" },
  { code: "fi", name: "Finland", flag: "🇫🇮", region: "Europe" },
  { code: "fr", name: "France", flag: "🇫🇷", region: "Europe" },
  { code: "ge", name: "Georgia", flag: "🇬🇪", region: "Europe" },
  { code: "de", name: "Germany", flag: "🇩🇪", region: "Europe" },
  { code: "gr", name: "Greece", flag: "🇬🇷", region: "Europe" },
  { code: "hu", name: "Hungary", flag: "🇭🇺", region: "Europe" },
  { code: "is", name: "Iceland", flag: "🇮🇸", region: "Europe" },
  { code: "ie", name: "Ireland", flag: "🇮🇪", region: "Europe" },
  { code: "it", name: "Italy", flag: "🇮🇹", region: "Europe" },
  { code: "xk", name: "Kosovo", flag: "🇽🇰", region: "Europe" },
  { code: "lv", name: "Latvia", flag: "🇱🇻", region: "Europe" },
  { code: "li", name: "Liechtenstein", flag: "🇱🇮", region: "Europe" },
  { code: "lt", name: "Lithuania", flag: "🇱🇹", region: "Europe" },
  { code: "lu", name: "Luxembourg", flag: "🇱🇺", region: "Europe" },
  { code: "mt", name: "Malta", flag: "🇲🇹", region: "Europe" },
  { code: "md", name: "Moldova", flag: "🇲🇩", region: "Europe" },
  { code: "mc", name: "Monaco", flag: "🇲🇨", region: "Europe" },
  { code: "me", name: "Montenegro", flag: "🇲🇪", region: "Europe" },
  { code: "nl", name: "Netherlands", flag: "🇳🇱", region: "Europe" },
  { code: "mk", name: "North Macedonia", flag: "🇲🇰", region: "Europe" },
  { code: "no", name: "Norway", flag: "🇳🇴", region: "Europe" },
  { code: "pl", name: "Poland", flag: "🇵🇱", region: "Europe" },
  { code: "pt", name: "Portugal", flag: "🇵🇹", region: "Europe" },
  { code: "ro", name: "Romania", flag: "🇷🇴", region: "Europe" },
  { code: "ru", name: "Russia", flag: "🇷🇺", region: "Europe" },
  { code: "rs", name: "Serbia", flag: "🇷🇸", region: "Europe" },
  { code: "sk", name: "Slovakia", flag: "🇸🇰", region: "Europe" },
  { code: "si", name: "Slovenia", flag: "🇸🇮", region: "Europe" },
  { code: "sm", name: "San Marino", flag: "🇸🇲", region: "Europe" },
  { code: "es", name: "Spain", flag: "🇪🇸", region: "Europe" },
  { code: "se", name: "Sweden", flag: "🇸🇪", region: "Europe" },
  { code: "ch", name: "Switzerland", flag: "🇨🇭", region: "Europe" },
  { code: "tr", name: "Turkey", flag: "🇹🇷", region: "Europe" },
  { code: "gb", name: "United Kingdom", flag: "🇬🇧", region: "Europe" },
  { code: "ua", name: "Ukraine", flag: "🇺🇦", region: "Europe" },
  { code: "va", name: "Vatican City", flag: "🇻🇦", region: "Europe" },
  // Africa
  { code: "dz", name: "Algeria", flag: "🇩🇿", region: "Africa" },
  { code: "ao", name: "Angola", flag: "🇦🇴", region: "Africa" },
  { code: "bj", name: "Benin", flag: "🇧🇯", region: "Africa" },
  { code: "bw", name: "Botswana", flag: "🇧🇼", region: "Africa" },
  { code: "bf", name: "Burkina Faso", flag: "🇧🇫", region: "Africa" },
  { code: "bi", name: "Burundi", flag: "🇧🇮", region: "Africa" },
  { code: "cm", name: "Cameroon", flag: "🇨🇲", region: "Africa" },
  { code: "cv", name: "Cape Verde", flag: "🇨🇻", region: "Africa" },
  { code: "cf", name: "Central African Republic", flag: "🇨🇫", region: "Africa" },
  { code: "td", name: "Chad", flag: "🇹🇩", region: "Africa" },
  { code: "km", name: "Comoros", flag: "🇰🇲", region: "Africa" },
  { code: "cg", name: "Congo", flag: "🇨🇬", region: "Africa" },
  { code: "cd", name: "DR Congo", flag: "🇨🇩", region: "Africa" },
  { code: "dj", name: "Djibouti", flag: "🇩🇯", region: "Africa" },
  { code: "eg", name: "Egypt", flag: "🇪🇬", region: "Africa" },
  { code: "gq", name: "Equatorial Guinea", flag: "🇬🇶", region: "Africa" },
  { code: "er", name: "Eritrea", flag: "🇪🇷", region: "Africa" },
  { code: "sz", name: "Eswatini", flag: "🇸🇿", region: "Africa" },
  { code: "et", name: "Ethiopia", flag: "🇪🇹", region: "Africa" },
  { code: "ga", name: "Gabon", flag: "🇬🇦", region: "Africa" },
  { code: "gm", name: "Gambia", flag: "🇬🇲", region: "Africa" },
  { code: "gh", name: "Ghana", flag: "🇬🇭", region: "Africa" },
  { code: "gn", name: "Guinea", flag: "🇬🇳", region: "Africa" },
  { code: "gw", name: "Guinea-Bissau", flag: "🇬🇼", region: "Africa" },
  { code: "ci", name: "Ivory Coast", flag: "🇨🇮", region: "Africa" },
  { code: "ke", name: "Kenya", flag: "🇰🇪", region: "Africa" },
  { code: "ls", name: "Lesotho", flag: "🇱🇸", region: "Africa" },
  { code: "lr", name: "Liberia", flag: "🇱🇷", region: "Africa" },
  { code: "ly", name: "Libya", flag: "🇱🇾", region: "Africa" },
  { code: "mg", name: "Madagascar", flag: "🇲🇬", region: "Africa" },
  { code: "mw", name: "Malawi", flag: "🇲🇼", region: "Africa" },
  { code: "ml", name: "Mali", flag: "🇲🇱", region: "Africa" },
  { code: "mr", name: "Mauritania", flag: "🇲🇷", region: "Africa" },
  { code: "mu", name: "Mauritius", flag: "🇲🇺", region: "Africa" },
  { code: "ma", name: "Morocco", flag: "🇲🇦", region: "Africa" },
  { code: "mz", name: "Mozambique", flag: "🇲🇿", region: "Africa" },
  { code: "na", name: "Namibia", flag: "🇳🇦", region: "Africa" },
  { code: "ne", name: "Niger", flag: "🇳🇪", region: "Africa" },
  { code: "ng", name: "Nigeria", flag: "🇳🇬", region: "Africa" },
  { code: "rw", name: "Rwanda", flag: "🇷🇼", region: "Africa" },
  { code: "st", name: "Sao Tome and Principe", flag: "🇸🇹", region: "Africa" },
  { code: "sn", name: "Senegal", flag: "🇸🇳", region: "Africa" },
  { code: "sc", name: "Seychelles", flag: "🇸🇨", region: "Africa" },
  { code: "sl", name: "Sierra Leone", flag: "🇸🇱", region: "Africa" },
  { code: "so", name: "Somalia", flag: "🇸🇴", region: "Africa" },
  { code: "za", name: "South Africa", flag: "🇿🇦", region: "Africa" },
  { code: "ss", name: "South Sudan", flag: "🇸🇸", region: "Africa" },
  { code: "sd", name: "Sudan", flag: "🇸🇩", region: "Africa" },
  { code: "tz", name: "Tanzania", flag: "🇹🇿", region: "Africa" },
  { code: "tg", name: "Togo", flag: "🇹🇬", region: "Africa" },
  { code: "tn", name: "Tunisia", flag: "🇹🇳", region: "Africa" },
  { code: "ug", name: "Uganda", flag: "🇺🇬", region: "Africa" },
  { code: "zm", name: "Zambia", flag: "🇿🇲", region: "Africa" },
  { code: "zw", name: "Zimbabwe", flag: "🇿🇼", region: "Africa" },
  // Americas
  { code: "ag", name: "Antigua and Barbuda", flag: "🇦🇬", region: "Americas" },
  { code: "ar", name: "Argentina", flag: "🇦🇷", region: "Americas" },
  { code: "aw", name: "Aruba", flag: "🇦🇼", region: "Americas" },
  { code: "bs", name: "Bahamas", flag: "🇧🇸", region: "Americas" },
  { code: "bb", name: "Barbados", flag: "🇧🇧", region: "Americas" },
  { code: "bz", name: "Belize", flag: "🇧🇿", region: "Americas" },
  { code: "bm", name: "Bermuda", flag: "🇧🇲", region: "Americas" },
  { code: "bo", name: "Bolivia", flag: "🇧🇴", region: "Americas" },
  { code: "br", name: "Brazil", flag: "🇧🇷", region: "Americas" },
  { code: "vg", name: "British Virgin Islands", flag: "🇻🇬", region: "Americas" },
  { code: "ca", name: "Canada", flag: "🇨🇦", region: "Americas" },
  { code: "ky", name: "Cayman Islands", flag: "🇰🇾", region: "Americas" },
  { code: "cl", name: "Chile", flag: "🇨🇱", region: "Americas" },
  { code: "co", name: "Colombia", flag: "🇨🇴", region: "Americas" },
  { code: "cr", name: "Costa Rica", flag: "🇨🇷", region: "Americas" },
  { code: "cu", name: "Cuba", flag: "🇨🇺", region: "Americas" },
  { code: "cw", name: "Curacao", flag: "🇨🇼", region: "Americas" },
  { code: "dm", name: "Dominica", flag: "🇩🇲", region: "Americas" },
  { code: "do", name: "Dominican Republic", flag: "🇩🇴", region: "Americas" },
  { code: "ec", name: "Ecuador", flag: "🇪🇨", region: "Americas" },
  { code: "sv", name: "El Salvador", flag: "🇸🇻", region: "Americas" },
  { code: "gl", name: "Greenland", flag: "🇬🇱", region: "Americas" },
  { code: "gd", name: "Grenada", flag: "🇬🇩", region: "Americas" },
  { code: "gp", name: "Guadeloupe", flag: "🇬🇵", region: "Americas" },
  { code: "gt", name: "Guatemala", flag: "🇬🇹", region: "Americas" },
  { code: "gy", name: "Guyana", flag: "🇬🇾", region: "Americas" },
  { code: "ht", name: "Haiti", flag: "🇭🇹", region: "Americas" },
  { code: "hn", name: "Honduras", flag: "🇭🇳", region: "Americas" },
  { code: "jm", name: "Jamaica", flag: "🇯🇲", region: "Americas" },
  { code: "mq", name: "Martinique", flag: "🇲🇶", region: "Americas" },
  { code: "mx", name: "Mexico", flag: "🇲🇽", region: "Americas" },
  { code: "ni", name: "Nicaragua", flag: "🇳🇮", region: "Americas" },
  { code: "pa", name: "Panama", flag: "🇵🇦", region: "Americas" },
  { code: "py", name: "Paraguay", flag: "🇵🇾", region: "Americas" },
  { code: "pe", name: "Peru", flag: "🇵🇪", region: "Americas" },
  { code: "pr", name: "Puerto Rico", flag: "🇵🇷", region: "Americas" },
  { code: "kn", name: "Saint Kitts and Nevis", flag: "🇰🇳", region: "Americas" },
  { code: "lc", name: "Saint Lucia", flag: "🇱🇨", region: "Americas" },
  { code: "vc", name: "Saint Vincent", flag: "🇻🇨", region: "Americas" },
  { code: "sx", name: "Sint Maarten", flag: "🇸🇽", region: "Americas" },
  { code: "sr", name: "Suriname", flag: "🇸🇷", region: "Americas" },
  { code: "tt", name: "Trinidad and Tobago", flag: "🇹🇹", region: "Americas" },
  { code: "tc", name: "Turks and Caicos", flag: "🇹🇨", region: "Americas" },
  { code: "us", name: "United States", flag: "🇺🇸", region: "Americas" },
  { code: "uy", name: "Uruguay", flag: "🇺🇾", region: "Americas" },
  { code: "vi", name: "US Virgin Islands", flag: "🇻🇮", region: "Americas" },
  { code: "ve", name: "Venezuela", flag: "🇻🇪", region: "Americas" },
  // Asia & Middle East
  { code: "az", name: "Azerbaijan", flag: "🇦🇿", region: "Asia" },
  { code: "bh", name: "Bahrain", flag: "🇧🇭", region: "Asia" },
  { code: "bd", name: "Bangladesh", flag: "🇧🇩", region: "Asia" },
  { code: "bn", name: "Brunei", flag: "🇧🇳", region: "Asia" },
  { code: "kh", name: "Cambodia", flag: "🇰🇭", region: "Asia" },
  { code: "cn", name: "China", flag: "🇨🇳", region: "Asia" },
  { code: "ge", name: "Georgia", flag: "🇬🇪", region: "Asia" },
  { code: "hk", name: "Hong Kong", flag: "🇭🇰", region: "Asia" },
  { code: "in", name: "India", flag: "🇮🇳", region: "Asia" },
  { code: "id", name: "Indonesia", flag: "🇮🇩", region: "Asia" },
  { code: "ir", name: "Iran", flag: "🇮🇷", region: "Asia" },
  { code: "iq", name: "Iraq", flag: "🇮🇶", region: "Asia" },
  { code: "il", name: "Israel", flag: "🇮🇱", region: "Asia" },
  { code: "jp", name: "Japan", flag: "🇯🇵", region: "Asia" },
  { code: "jo", name: "Jordan", flag: "🇯🇴", region: "Asia" },
  { code: "kz", name: "Kazakhstan", flag: "🇰🇿", region: "Asia" },
  { code: "kr", name: "South Korea", flag: "🇰🇷", region: "Asia" },
  { code: "kw", name: "Kuwait", flag: "🇰🇼", region: "Asia" },
  { code: "kg", name: "Kyrgyzstan", flag: "🇰🇬", region: "Asia" },
  { code: "la", name: "Laos", flag: "🇱🇦", region: "Asia" },
  { code: "lb", name: "Lebanon", flag: "🇱🇧", region: "Asia" },
  { code: "my", name: "Malaysia", flag: "🇲🇾", region: "Asia" },
  { code: "mv", name: "Maldives", flag: "🇲🇻", region: "Asia" },
  { code: "mn", name: "Mongolia", flag: "🇲🇳", region: "Asia" },
  { code: "mm", name: "Myanmar", flag: "🇲🇲", region: "Asia" },
  { code: "np", name: "Nepal", flag: "🇳🇵", region: "Asia" },
  { code: "om", name: "Oman", flag: "🇴🇲", region: "Asia" },
  { code: "pk", name: "Pakistan", flag: "🇵🇰", region: "Asia" },
  { code: "ph", name: "Philippines", flag: "🇵🇭", region: "Asia" },
  { code: "qa", name: "Qatar", flag: "🇶🇦", region: "Asia" },
  { code: "sa", name: "Saudi Arabia", flag: "🇸🇦", region: "Asia" },
  { code: "sg", name: "Singapore", flag: "🇸🇬", region: "Asia" },
  { code: "lk", name: "Sri Lanka", flag: "🇱🇰", region: "Asia" },
  { code: "sy", name: "Syria", flag: "🇸🇾", region: "Asia" },
  { code: "tw", name: "Taiwan", flag: "🇹🇼", region: "Asia" },
  { code: "tj", name: "Tajikistan", flag: "🇹🇯", region: "Asia" },
  { code: "th", name: "Thailand", flag: "🇹🇭", region: "Asia" },
  { code: "ae", name: "United Arab Emirates", flag: "🇦🇪", region: "Asia" },
  { code: "uz", name: "Uzbekistan", flag: "🇺🇿", region: "Asia" },
  { code: "vn", name: "Vietnam", flag: "🇻🇳", region: "Asia" },
  { code: "ye", name: "Yemen", flag: "🇾🇪", region: "Asia" },
  // Oceania
  { code: "au", name: "Australia", flag: "🇦🇺", region: "Oceania" },
  { code: "fj", name: "Fiji", flag: "🇫🇯", region: "Oceania" },
  { code: "pf", name: "French Polynesia", flag: "🇵🇫", region: "Oceania" },
  { code: "gu", name: "Guam", flag: "🇬🇺", region: "Oceania" },
  { code: "nc", name: "New Caledonia", flag: "🇳🇨", region: "Oceania" },
  { code: "nz", name: "New Zealand", flag: "🇳🇿", region: "Oceania" },
  { code: "pg", name: "Papua New Guinea", flag: "🇵🇬", region: "Oceania" },
  { code: "ws", name: "Samoa", flag: "🇼🇸", region: "Oceania" },
  { code: "sb", name: "Solomon Islands", flag: "🇸🇧", region: "Oceania" },
  { code: "to", name: "Tonga", flag: "🇹🇴", region: "Oceania" },
  { code: "vu", name: "Vanuatu", flag: "🇻🇺", region: "Oceania" },
]

export const POPULAR_COUNTRY_CODES = ["dk", "us", "gb", "de", "th", "ae", "fr", "nl", "se", "no", "es", "it", "ch", "pt", "pl"]

export const SUPPORTED_CODES = new Set(SUPPORTED_COUNTRIES.map(c => c.code))

export function getCountry(code: string): Country | undefined {
  return SUPPORTED_COUNTRIES.find(c => c.code === code.toLowerCase())
}

/**
 * Build a Supabase OR-filter string covering all country variants:
 * ISO code (dk/DK) + full name (Denmark) + lowercase name (denmark)
 * Input can be ISO code ("dk") or full name ("Denmark")
 */
export function buildCountryOrFilter(input: string): string {
  const byCode = SUPPORTED_COUNTRIES.find(c => c.code === input.toLowerCase())
  const byName = SUPPORTED_COUNTRIES.find(c => c.name.toLowerCase() === input.toLowerCase())
  const c = byCode ?? byName

  const variants = c
    ? [c.name, c.name.toLowerCase(), c.code.toUpperCase(), c.code.toLowerCase()]
    : [input, input.toLowerCase(), input.toUpperCase(), input.toUpperCase().slice(0, 2)]

  return [...new Set(variants.filter(Boolean))]
    .map(v => `country.eq.${v}`)
    .join(",")
}

/**
 * Returns an array of all country DB variants for use with Supabase .in()
 * Input: ISO code ("dk") or full name ("Denmark")
 */
export function getCountryVariants(input: string): string[] {
  const byCode = SUPPORTED_COUNTRIES.find(c => c.code === input.toLowerCase())
  const byName = SUPPORTED_COUNTRIES.find(c => c.name.toLowerCase() === input.toLowerCase())
  const c = byCode ?? byName

  const variants = c
    ? [c.name, c.name.toLowerCase(), c.code.toUpperCase(), c.code.toLowerCase()]
    : [input, input.toLowerCase(), input.toUpperCase()]

  return [...new Set(variants.filter(Boolean))]
}

export function getCountryByName(name: string): Country | undefined {
  return SUPPORTED_COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase())
}

export function slugify(text: string): string {
  return text.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "")
}

// ── Full country list (hardcoded) ──────────────────────────────────────
export interface CountryEntry { name: string; code: string }

export const COUNTRIES: { europe: CountryEntry[]; worldwide: CountryEntry[] } = {
  europe: [
    { name: "Albania", code: "al" },
    { name: "Andorra", code: "ad" },
    { name: "Armenia", code: "am" },
    { name: "Austria", code: "at" },
    { name: "Belarus", code: "by" },
    { name: "Belgium", code: "be" },
    { name: "Bosnia and Herzegovina", code: "ba" },
    { name: "Bulgaria", code: "bg" },
    { name: "Croatia", code: "hr" },
    { name: "Cyprus", code: "cy" },
    { name: "Czech Republic", code: "cz" },
    { name: "Denmark", code: "dk" },
    { name: "Estonia", code: "ee" },
    { name: "Finland", code: "fi" },
    { name: "France", code: "fr" },
    { name: "Georgia", code: "ge" },
    { name: "Germany", code: "de" },
    { name: "Greece", code: "gr" },
    { name: "Hungary", code: "hu" },
    { name: "Iceland", code: "is" },
    { name: "Ireland", code: "ie" },
    { name: "Italy", code: "it" },
    { name: "Kosovo", code: "xk" },
    { name: "Latvia", code: "lv" },
    { name: "Liechtenstein", code: "li" },
    { name: "Lithuania", code: "lt" },
    { name: "Luxembourg", code: "lu" },
    { name: "Malta", code: "mt" },
    { name: "Moldova", code: "md" },
    { name: "Monaco", code: "mc" },
    { name: "Montenegro", code: "me" },
    { name: "Netherlands", code: "nl" },
    { name: "North Macedonia", code: "mk" },
    { name: "Norway", code: "no" },
    { name: "Poland", code: "pl" },
    { name: "Portugal", code: "pt" },
    { name: "Romania", code: "ro" },
    { name: "Russia", code: "ru" },
    { name: "San Marino", code: "sm" },
    { name: "Serbia", code: "rs" },
    { name: "Slovakia", code: "sk" },
    { name: "Slovenia", code: "si" },
    { name: "Spain", code: "es" },
    { name: "Sweden", code: "se" },
    { name: "Switzerland", code: "ch" },
    { name: "Turkey", code: "tr" },
    { name: "Ukraine", code: "ua" },
    { name: "United Kingdom", code: "gb" },
    { name: "Vatican City", code: "va" },
  ],
  worldwide: [
    { name: "Algeria", code: "dz" },
    { name: "Angola", code: "ao" },
    { name: "Antigua and Barbuda", code: "ag" },
    { name: "Argentina", code: "ar" },
    { name: "Aruba", code: "aw" },
    { name: "Australia", code: "au" },
    { name: "Azerbaijan", code: "az" },
    { name: "Bahamas", code: "bs" },
    { name: "Bahrain", code: "bh" },
    { name: "Bangladesh", code: "bd" },
    { name: "Barbados", code: "bb" },
    { name: "Belize", code: "bz" },
    { name: "Benin", code: "bj" },
    { name: "Bermuda", code: "bm" },
    { name: "Bolivia", code: "bo" },
    { name: "Botswana", code: "bw" },
    { name: "Brazil", code: "br" },
    { name: "British Virgin Islands", code: "vg" },
    { name: "Brunei", code: "bn" },
    { name: "Burkina Faso", code: "bf" },
    { name: "Burundi", code: "bi" },
    { name: "Cambodia", code: "kh" },
    { name: "Cameroon", code: "cm" },
    { name: "Canada", code: "ca" },
    { name: "Cape Verde", code: "cv" },
    { name: "Cayman Islands", code: "ky" },
    { name: "Central African Republic", code: "cf" },
    { name: "Chad", code: "td" },
    { name: "Chile", code: "cl" },
    { name: "China", code: "cn" },
    { name: "Colombia", code: "co" },
    { name: "Comoros", code: "km" },
    { name: "Congo", code: "cg" },
    { name: "Costa Rica", code: "cr" },
    { name: "Cuba", code: "cu" },
    { name: "Curacao", code: "cw" },
    { name: "Djibouti", code: "dj" },
    { name: "Dominica", code: "dm" },
    { name: "Dominican Republic", code: "do" },
    { name: "DR Congo", code: "cd" },
    { name: "Ecuador", code: "ec" },
    { name: "Egypt", code: "eg" },
    { name: "El Salvador", code: "sv" },
    { name: "Equatorial Guinea", code: "gq" },
    { name: "Eritrea", code: "er" },
    { name: "Eswatini", code: "sz" },
    { name: "Ethiopia", code: "et" },
    { name: "Fiji", code: "fj" },
    { name: "French Polynesia", code: "pf" },
    { name: "Gabon", code: "ga" },
    { name: "Gambia", code: "gm" },
    { name: "Ghana", code: "gh" },
    { name: "Greenland", code: "gl" },
    { name: "Grenada", code: "gd" },
    { name: "Guadeloupe", code: "gp" },
    { name: "Guam", code: "gu" },
    { name: "Guatemala", code: "gt" },
    { name: "Guinea", code: "gn" },
    { name: "Guinea-Bissau", code: "gw" },
    { name: "Guyana", code: "gy" },
    { name: "Haiti", code: "ht" },
    { name: "Honduras", code: "hn" },
    { name: "Hong Kong", code: "hk" },
    { name: "India", code: "in" },
    { name: "Indonesia", code: "id" },
    { name: "Iran", code: "ir" },
    { name: "Iraq", code: "iq" },
    { name: "Israel", code: "il" },
    { name: "Ivory Coast", code: "ci" },
    { name: "Jamaica", code: "jm" },
    { name: "Japan", code: "jp" },
    { name: "Jordan", code: "jo" },
    { name: "Kazakhstan", code: "kz" },
    { name: "Kenya", code: "ke" },
    { name: "Kuwait", code: "kw" },
    { name: "Kyrgyzstan", code: "kg" },
    { name: "Laos", code: "la" },
    { name: "Lebanon", code: "lb" },
    { name: "Lesotho", code: "ls" },
    { name: "Liberia", code: "lr" },
    { name: "Libya", code: "ly" },
    { name: "Madagascar", code: "mg" },
    { name: "Malawi", code: "mw" },
    { name: "Malaysia", code: "my" },
    { name: "Maldives", code: "mv" },
    { name: "Mali", code: "ml" },
    { name: "Martinique", code: "mq" },
    { name: "Mauritania", code: "mr" },
    { name: "Mauritius", code: "mu" },
    { name: "Mexico", code: "mx" },
    { name: "Mongolia", code: "mn" },
    { name: "Morocco", code: "ma" },
    { name: "Mozambique", code: "mz" },
    { name: "Myanmar", code: "mm" },
    { name: "Namibia", code: "na" },
    { name: "Nepal", code: "np" },
    { name: "New Caledonia", code: "nc" },
    { name: "New Zealand", code: "nz" },
    { name: "Nicaragua", code: "ni" },
    { name: "Niger", code: "ne" },
    { name: "Nigeria", code: "ng" },
    { name: "Oman", code: "om" },
    { name: "Pakistan", code: "pk" },
    { name: "Panama", code: "pa" },
    { name: "Papua New Guinea", code: "pg" },
    { name: "Paraguay", code: "py" },
    { name: "Peru", code: "pe" },
    { name: "Philippines", code: "ph" },
    { name: "Puerto Rico", code: "pr" },
    { name: "Qatar", code: "qa" },
    { name: "Rwanda", code: "rw" },
    { name: "Saint Kitts and Nevis", code: "kn" },
    { name: "Saint Lucia", code: "lc" },
    { name: "Saint Vincent", code: "vc" },
    { name: "Samoa", code: "ws" },
    { name: "Sao Tome and Principe", code: "st" },
    { name: "Saudi Arabia", code: "sa" },
    { name: "Senegal", code: "sn" },
    { name: "Seychelles", code: "sc" },
    { name: "Sierra Leone", code: "sl" },
    { name: "Singapore", code: "sg" },
    { name: "Sint Maarten", code: "sx" },
    { name: "Solomon Islands", code: "sb" },
    { name: "Somalia", code: "so" },
    { name: "South Africa", code: "za" },
    { name: "South Korea", code: "kr" },
    { name: "South Sudan", code: "ss" },
    { name: "Sri Lanka", code: "lk" },
    { name: "Sudan", code: "sd" },
    { name: "Suriname", code: "sr" },
    { name: "Syria", code: "sy" },
    { name: "Taiwan", code: "tw" },
    { name: "Tajikistan", code: "tj" },
    { name: "Tanzania", code: "tz" },
    { name: "Thailand", code: "th" },
    { name: "Togo", code: "tg" },
    { name: "Tonga", code: "to" },
    { name: "Trinidad and Tobago", code: "tt" },
    { name: "Tunisia", code: "tn" },
    { name: "Turks and Caicos", code: "tc" },
    { name: "Uganda", code: "ug" },
    { name: "United Arab Emirates", code: "ae" },
    { name: "United States", code: "us" },
    { name: "Uruguay", code: "uy" },
    { name: "US Virgin Islands", code: "vi" },
    { name: "Uzbekistan", code: "uz" },
    { name: "Vanuatu", code: "vu" },
    { name: "Venezuela", code: "ve" },
    { name: "Vietnam", code: "vn" },
    { name: "Yemen", code: "ye" },
    { name: "Zambia", code: "zm" },
    { name: "Zimbabwe", code: "zw" },
  ],
}

// All countries flat + extended SUPPORTED_CODES
export const ALL_COUNTRIES: CountryEntry[] = [...COUNTRIES.europe, ...COUNTRIES.worldwide]
export const ALL_COUNTRY_CODES = new Set(ALL_COUNTRIES.map(c => c.code))
export const EXTENDED_SUPPORTED_CODES = new Set([...SUPPORTED_CODES, ...ALL_COUNTRY_CODES])

export function getCountryEntryByName(name: string): CountryEntry | undefined {
  return ALL_COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase())
}

export function getCountryEntryByCode(code: string): CountryEntry | undefined {
  return ALL_COUNTRIES.find(c => c.code === code.toLowerCase())
}

// Emoji flag from 2-letter ISO code
export function codeToEmoji(code: string): string {
  const c = code.toUpperCase()
  if (c.length !== 2) return "🌍"
  return String.fromCodePoint(...[...c].map(ch => 0x1F1E6 - 65 + ch.charCodeAt(0)))
}

// ── Hardcoded cities per country ───────────────────────────────────────
export const COUNTRY_CITIES: Record<string, string[]> = {
  dk: ["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens","Vejle","Roskilde"],
  se: ["Stockholm","Gothenburg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Jönköping","Norrköping"],
  no: ["Oslo","Bergen","Trondheim","Stavanger","Drammen","Fredrikstad","Kristiansand","Sandnes","Tromsø","Sarpsborg"],
  fi: ["Helsinki","Espoo","Tampere","Vantaa","Oulu","Turku","Jyväskylä","Lahti","Kuopio","Pori"],
  de: ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Leipzig","Dortmund","Essen","Bremen","Dresden","Hanover","Nuremberg","Duisburg"],
  uk: ["London","Manchester","Birmingham","Glasgow","Leeds","Liverpool","Edinburgh","Bristol","Sheffield","Cardiff","Belfast","Newcastle","Nottingham","Leicester"],
  fr: ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Strasbourg","Montpellier","Bordeaux","Lille","Rennes","Cannes","Monaco","Grenoble","Saint-Tropez","Antibes"],
  es: ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Las Palmas","Bilbao","Alicante","Ibiza","Marbella","Tenerife","Gran Canaria","Benidorm","Torrevieja","Fuengirola"],
  it: ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Venice","Verona","Rimini"],
  nl: ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Groningen","Tilburg","Almere","Breda"],
  be: ["Brussels","Antwerp","Ghent","Charleroi","Liège","Bruges","Namur"],
  ch: ["Zurich","Geneva","Basel","Bern","Lausanne","Lucerne","St. Gallen","Lugano"],
  at: ["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt"],
  pl: ["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk","Szczecin","Katowice","Lublin"],
  cz: ["Prague","Brno","Ostrava","Plzeň","Liberec","Olomouc"],
  hu: ["Budapest","Debrecen","Miskolc","Szeged","Pécs","Győr"],
  ro: ["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța","Brașov","Sibiu","Sinaia"],
  bg: ["Sofia","Plovdiv","Varna","Burgas","Ruse","Sunny Beach"],
  hr: ["Zagreb","Split","Rijeka","Osijek","Zadar","Dubrovnik","Pula"],
  gr: ["Athens","Thessaloniki","Patras","Heraklion","Larissa","Rhodes","Mykonos","Santorini"],
  pt: ["Lisbon","Porto","Faro","Braga","Setúbal","Coimbra","Albufeira","Portimao","Lagos","Cascais","Vilamoura","Funchal"],
  tr: ["Istanbul","Ankara","Izmir","Antalya","Bursa","Adana","Gaziantep","Alanya","Bodrum","Mugla","Marmaris","Kusadasi","Trabzon"],
  ru: ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Kazan","Sochi","Krasnodar","Rostov-on-Don"],
  ua: ["Kiev","Kyiv","Kharkiv","Odessa","Dnipro","Lviv","Zaporizhzhia","Mykolaiv"],
  rs: ["Belgrade","Novi Sad","Niš","Subotica","Kragujevac","Čačak"],
  al: ["Tirana","Durrës","Vlorë","Shkodër","Sarandë","Elbasan"],
  ae: ["Dubai","Abu Dhabi","Sharjah","Ajman","Ras Al Khaimah"],
  sa: ["Riyadh","Jeddah","Mecca","Medina","Dammam","Khobar"],
  th: ["Bangkok","Pattaya","Phuket","Chiang Mai","Koh Samui"],
  jp: ["Tokyo","Osaka","Kyoto","Nagoya","Sapporo","Fukuoka","Yokohama"],
  us: ["New York","Los Angeles","Miami","Las Vegas","Chicago","Houston","Phoenix","San Francisco"],
  ca: ["Toronto","Vancouver","Montreal","Calgary","Ottawa","Edmonton"],
  au: ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Gold Coast"],
  br: ["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Manaus"],
  mx: ["Mexico City","Cancún","Guadalajara","Monterrey","Tijuana","Playa del Carmen"],
  cn: ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Hong Kong"],
  in: ["Mumbai","Delhi","Bangalore","Hyderabad","Chennai","Kolkata","Goa"],
  eg: ["Cairo","Alexandria","Luxor","Hurghada","Sharm El Sheikh"],
  ma: ["Casablanca","Marrakech","Rabat","Fes","Agadir","Tangier"],
  ph: ["Manila","Cebu","Davao","Angeles","Makati"],
  id: ["Jakarta","Bali","Surabaya","Bandung","Medan"],
  my: ["Kuala Lumpur","Penang","Johor Bahru","Kota Kinabalu"],
  sg: ["Singapore"],
  il: ["Tel Aviv","Jerusalem","Haifa","Eilat"],
  lb: ["Beirut","Jounieh","Byblos"],
  za: ["Johannesburg","Cape Town","Durban","Pretoria"],
  ng: ["Lagos","Abuja","Port Harcourt","Kano"],
  ke: ["Nairobi","Mombasa","Kisumu"],
  gh: ["Accra","Kumasi","Takoradi"],
  ar: ["Buenos Aires","Córdoba","Rosario","Mendoza","Mar del Plata"],
  cl: ["Santiago","Valparaíso","Concepción","Antofagasta"],
  co: ["Bogotá","Medellín","Cali","Cartagena","Barranquilla"],
  pe: ["Lima","Cusco","Arequipa","Trujillo"],
  tw: ["Taipei","Kaohsiung","Taichung","Tainan"],
  kr: ["Seoul","Busan","Incheon","Daegu","Daejeon"],
  kz: ["Almaty","Nur-Sultan","Shymkent"],
  uz: ["Tashkent","Samarkand","Bukhara"],
  by: ["Minsk","Gomel","Mogilev","Vitebsk","Grodno","Brest"],
  lv: ["Riga","Daugavpils","Liepāja","Jelgava","Jūrmala"],
  lt: ["Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys"],
  ee: ["Tallinn","Tartu","Narva","Pärnu"],
  sk: ["Bratislava","Košice","Prešov","Žilina","Banská Bystrica"],
  si: ["Ljubljana","Maribor","Celje","Koper","Kranj"],
  ba: ["Sarajevo","Banja Luka","Mostar","Tuzla","Zenica"],
  mk: ["Skopje","Bitola","Kumanovo","Tetovo"],
  me: ["Podgorica","Budva","Bar","Kotor","Herceg Novi","Tivat"],
  am: ["Yerevan","Gyumri","Vanadzor","Vagharshapat"],
  ge: ["Tbilisi","Batumi","Kutaisi","Rustavi"],
  az: ["Baku","Ganja","Sumqayit"],
  qa: ["Doha","Al Rayyan"],
  kw: ["Kuwait City","Salmiya","Hawalli"],
  bh: ["Manama","Muharraq","Riffa"],
  om: ["Muscat","Salalah","Sohar"],
  jo: ["Amman","Aqaba","Irbid","Zarqa"],
  lk: ["Colombo","Kandy","Galle","Negombo"],
  np: ["Kathmandu","Pokhara","Lalitpur"],
  bd: ["Dhaka","Chittagong","Sylhet"],
  pk: ["Karachi","Lahore","Islamabad","Faisalabad"],
  kh: ["Phnom Penh","Siem Reap","Sihanoukville"],
  vn: ["Ho Chi Minh City","Hanoi","Da Nang","Nha Trang","Hội An","Phu Quoc","Hue"],
  nz: ["Auckland","Wellington","Christchurch","Queenstown"],
  cr: ["San José","Tamarindo","Jacó","Liberia"],
  pa: ["Panama City","Colón","David"],
  ec: ["Quito","Guayaquil","Cuenca"],
  tn: ["Tunis","Sfax","Sousse","Hammamet"],
  dz: ["Algiers","Oran","Constantine"],
  sn: ["Dakar","Saint-Louis","Thiès"],
  cm: ["Douala","Yaoundé","Bafoussam"],
  ao: ["Luanda","Huambo","Benguela"],
  ug: ["Kampala","Entebbe","Jinja"],
  // New countries
  bj: ["Cotonou","Porto-Novo","Parakou","Abomey"],
  bn: ["Bandar Seri Begawan","Kuala Belait","Seria"],
  bf: ["Ouagadougou","Bobo-Dioulasso","Koudougou"],
  cv: ["Praia","Mindelo","Espargos","Santa Maria"],
  cb: ["Havana","Nassau","Bridgetown","Kingston","Port of Spain","Santo Domingo","San Juan"],
  cg: ["Brazzaville","Pointe-Noire","Dolisie","Nkayi"],
  cd: ["Kinshasa","Lubumbashi","Mbuji-Mayi","Goma","Bukavu"],
  et: ["Addis Ababa","Dire Dawa","Hawassa","Bahir Dar","Mekelle"],
  gm: ["Banjul","Serekunda","Brikama","Farafenni"],
  gt: ["Guatemala City","Antigua","Quetzaltenango","Flores","Livingston"],
  ir: ["Tehran","Mashhad","Isfahan","Tabriz","Shiraz","Ahvaz"],
  iq: ["Baghdad","Basra","Mosul","Erbil","Sulaymaniyah","Najaf"],
  kg: ["Bishkek","Osh","Jalal-Abad","Karakol"],
  la: ["Vientiane","Luang Prabang","Pakse","Savannakhet"],
  mv: ["Malé","Hulhumalé","Addu City","Maafushi"],
  ml: ["Bamako","Sikasso","Mopti","Gao","Timbuktu"],
  mu: ["Port Louis","Beau Bassin","Vacoas","Curepipe","Grand Baie"],
  mn: ["Ulaanbaatar","Erdenet","Darkhan","Choibalsan"],
  mz: ["Maputo","Matola","Beira","Nampula","Pemba"],
  ni: ["Managua","León","Granada","Masaya","Estelí"],
  py: ["Asunción","Ciudad del Este","San Lorenzo","Luque","Lambaré"],
  sc: ["Victoria","Anse Boileau","Beau Vallon","Praslin","La Digue"],
  tz: ["Dar es Salaam","Zanzibar","Arusha","Mwanza","Moshi","Dodoma"],
  tg: ["Lomé","Sokodé","Kara","Atakpamé"],
  uy: ["Montevideo","Punta del Este","Colonia del Sacramento","Salto","Maldonado"],
  ve: ["Caracas","Maracaibo","Valencia","Barquisimeto","Maracay","Mérida"],
  zm: ["Lusaka","Kitwe","Ndola","Livingstone","Kabwe"],
  af: ["Kabul","Kandahar","Herat","Mazar-i-Sharif"],
  // Additional Europe countries
  ad:  ["Andorra la Vella","Escaldes-Engordany","Encamp","La Massana"],
  cy: ["Nicosia","Limassol","Larnaca","Paphos","Famagusta","Ayia Napa"],
  is: ["Reykjavik","Akureyri","Keflavik"],
  ie: ["Dublin","Cork","Limerick","Galway","Waterford","Belfast"],
  xk: ["Pristina","Prizren","Peja","Mitrovica"],
  li: ["Vaduz","Schaan","Balzers"],
  lu: ["Luxembourg City","Esch-sur-Alzette","Differdange","Dudelange"],
  mt: ["Valletta","Sliema","St. Julian's","Msida","Birkirkara"],
  md: ["Chișinău","Tiraspol","Bălți","Bender"],
  mc: ["Monaco-Ville","Monte-Carlo","La Condamine","Fontvieille"],
}
