export const mockAnnonceAd = {
  id: 1,
  name: "Sofia Milano",
  verified: true,
  lastSeen: "2 hours ago",
  country: "Danmark",
  category: "Escort",
  city: "København",
  age: 24,
  gender: "Female",
  languages: ["Dansk", "Engelsk"],
  about: "Hej, jeg er Sofia Milano — en professionel og diskret ledsager baseret i København. Jeg tilbyder en uforglemmelig oplevelse for den sofistikerede herre. Jeg er velrejst, uddannet og flydende i både dansk og engelsk. Uanset om du leder efter en middagsdate, rejseledsager eller et privat møde, er jeg det perfekte valg. Jeg sætter stor pris på diskretion, god hygiejne og gensidig respekt. Kontakt mig gerne for at aftale et møde — jeg ser frem til at høre fra dig.",
  images: [
    "https://picsum.photos/800/600?random=40",
    "https://picsum.photos/800/600?random=41",
    "https://picsum.photos/800/600?random=42",
    "https://picsum.photos/800/600?random=43",
    "https://picsum.photos/800/600?random=44",
    "https://picsum.photos/800/600?random=45",
  ],
  totalPhotos: 20,
  hasVoiceMessage: true,
  rates: [
    { duration: "1 time", price: "$500" },
    { duration: "2 timer", price: "$900" },
    { duration: "Overnat", price: "$2.500" },
    { duration: "Weekend", price: "$5.000" },
  ],
  services: ["Dinner dates", "Social events", "Travel companion", "Private meetings", "Weekend getaways"],
  contact: {
    phone: "+45 XX XX XX XX",
    whatsapp: "+45 XX XX XX XX",
    telegram: "@sofiamilano",
    snapchat: "sofia.milano",
    email: "sofia@redlightad.com",
  },
};

export const mockListings = [
  { id: 101, title: "Jessica - New York Elite Escort", image: "https://picsum.photos/200/200?random=50", verified: true, description: "Luxury companion in Manhattan. Available for upscale events and private meetings.", hasVoice: true, hasVideo: true, age: 26, gender: "Female", category: "Escort", country: "United States", region: "New York", city: "New York City", language: "English", premium_tier: "vip" as const },
  { id: 102, title: "Brandon - LA Companion", image: "https://picsum.photos/200/200?random=51", verified: false, description: "Social companion available in Los Angeles. Travel-friendly.", hasVoice: false, age: 31, gender: "Male", category: "Companion", country: "United States", region: "California", city: "Los Angeles", language: "English", premium_tier: null },
  { id: 103, title: "Mia - Miami Beach", image: "https://picsum.photos/200/200?random=52", verified: true, description: "Fun and spontaneous. Available for parties and private events in Miami.", hasVoice: true, age: 23, gender: "Female", category: "Escort", country: "United States", region: "Florida", city: "Miami", language: "English, Spanish", premium_tier: null },
  { id: 104, title: "Charlotte - London VIP", image: "https://picsum.photos/200/200?random=53", verified: true, description: "Sophisticated London companion. Discreet and professional.", hasVoice: true, hasVideo: true, age: 28, gender: "Female", category: "Escort", country: "United Kingdom", region: "England", city: "London", language: "English", premium_tier: "featured" as const },
  { id: 105, title: "Liam - Manchester", image: "https://picsum.photos/200/200?random=54", verified: false, description: "Male escort available in Manchester and surrounding areas.", hasVoice: false, age: 29, gender: "Male", category: "Companion", country: "United Kingdom", region: "England", city: "Manchester", language: "English", premium_tier: null },
  { id: 106, title: "Sofia - København", image: "https://picsum.photos/200/200?random=55", verified: true, description: "Diskret og professionel ledsager i København centrum.", hasVoice: true, hasVideo: true, age: 24, gender: "Female", category: "Escort", country: "Denmark", region: "", city: "Copenhagen", language: "Danish, English", premium_tier: "featured" as const },
  { id: 107, title: "Luna - Aarhus", image: "https://picsum.photos/200/200?random=56", verified: true, description: "Tilgængelig for private møder og sociale events i Aarhus.", hasVoice: false, age: 22, gender: "Female", category: "Massage", country: "Denmark", region: "", city: "Aarhus", language: "Danish", premium_tier: null },
  { id: 108, title: "Lena - Berlin Model", image: "https://picsum.photos/200/200?random=57", verified: true, description: "Elegante Begleiterin für Geschäftsreisen und private Treffen in Berlin.", hasVoice: true, age: 27, gender: "Female", category: "Escort", country: "Germany", region: "Berlin", city: "Berlin", language: "German, English", premium_tier: null },
  { id: 109, title: "Klaus - München", image: "https://picsum.photos/200/200?random=58", verified: false, description: "Diskrete männliche Begleitung in München verfügbar.", hasVoice: false, age: 33, gender: "Male", category: "Companion", country: "Germany", region: "Bavaria", city: "Munich", language: "German", premium_tier: null },
  { id: 110, title: "Emma - Sydney Escort", image: "https://picsum.photos/200/200?random=59", verified: true, description: "Premium companion in Sydney CBD. Available for dinner dates and travel.", hasVoice: true, hasVideo: true, age: 25, gender: "Female", category: "Escort", country: "Australia", region: "New South Wales", city: "Sydney", language: "English", premium_tier: "vip" as const },
  { id: 111, title: "Olivia - Melbourne", image: "https://picsum.photos/200/200?random=60", verified: true, description: "Charming and witty companion based in Melbourne.", hasVoice: true, age: 27, gender: "Female", category: "Companion", country: "Australia", region: "Victoria", city: "Melbourne", language: "English", premium_tier: null },
  { id: 112, title: "Isabelle - Toronto", image: "https://picsum.photos/200/200?random=61", verified: true, description: "French-Canadian companion in Toronto. Bilingual and well-traveled.", hasVoice: false, age: 26, gender: "Female", category: "Escort", country: "Canada", region: "Ontario", city: "Toronto", language: "English, French", premium_tier: null },
  { id: 113, title: "Marcus - Vancouver", image: "https://picsum.photos/200/200?random=62", verified: false, description: "Available for social events and private meetings in Vancouver.", hasVoice: false, age: 30, gender: "Male", category: "Companion", country: "Canada", region: "British Columbia", city: "Vancouver", language: "English", premium_tier: null },
  { id: 114, title: "Anne - Amsterdam", image: "https://picsum.photos/200/200?random=63", verified: true, description: "Professional companion in Amsterdam. Discreet and elegant.", hasVoice: true, age: 25, gender: "Female", category: "Escort", country: "Netherlands", region: "North Holland", city: "Amsterdam", language: "Dutch, English", premium_tier: null },
  { id: 115, title: "Roos - Rotterdam", image: "https://picsum.photos/200/200?random=64", verified: true, description: "Available for dinner dates and exclusive private meetings in Rotterdam.", hasVoice: false, age: 28, gender: "Female", category: "Massage", country: "Netherlands", region: "South Holland", city: "Rotterdam", language: "Dutch, English", premium_tier: null },
]

export const mockAd = {
  id: 1,
  name: "Sofia",
  verified: true,
  country: "Denmark",
  category: "Escort",
  city: "Copenhagen",
  age: 24,
  gender: "Female",
  languages: ["Danish", "English"],
  description:
    "Hi, I am Sofia — a professional and discreet companion based in Copenhagen. I offer an unforgettable experience for the sophisticated gentleman. I am well-traveled, educated, and fluent in both Danish and English. Whether you are looking for a dinner date, travel companion, or private meeting, I am the perfect choice.",
  images: [
    "https://picsum.photos/800/600?random=30",
    "https://picsum.photos/800/600?random=31",
    "https://picsum.photos/800/600?random=32",
    "https://picsum.photos/800/600?random=33",
    "https://picsum.photos/800/600?random=34",
    "https://picsum.photos/800/600?random=35",
  ],
  totalPhotos: 20,
  hasVoiceMessage: true,
  hasVideo: true,
  rates: [
    { duration: "1 Hour", price: "2.000 DKK" },
    { duration: "2 Hours", price: "3.500 DKK" },
    { duration: "Overnight", price: "8.000 DKK" },
    { duration: "Weekend", price: "20.000 DKK" },
  ],
  services: [
    "GFE",
    "Dinner Date",
    "Travel Companion",
    "Overnight",
    "BDSM",
    "Massage",
    "Role Play",
    "Striptease",
  ],
  contact: {
    phone: "+45 XX XX XX XX",
    whatsapp: "+45 XX XX XX XX",
    telegram: "@sofiacph",
    email: "sofia@redlightad.com",
  },
};
