export const mockAd = {
  id: 1,
  name: "Sofia",
  verified: true,
  country: "Denmark",
  category: "Escort",
  city: "Copenhagen",
  age: 24,
  gender: "Female",
  languages: ["Danish", "English"],
  description:
    "Hi, I am Sofia — a professional and discreet companion based in Copenhagen. I offer an unforgettable experience for the sophisticated gentleman. I am well-traveled, educated, and fluent in both Danish and English. Whether you are looking for a dinner date, travel companion, or private meeting, I am the perfect choice.",
  images: [
    "https://picsum.photos/800/600?random=30",
    "https://picsum.photos/800/600?random=31",
    "https://picsum.photos/800/600?random=32",
    "https://picsum.photos/800/600?random=33",
    "https://picsum.photos/800/600?random=34",
    "https://picsum.photos/800/600?random=35",
  ],
  totalPhotos: 20,
  hasVoiceMessage: true,
  hasVideo: true,
  rates: [
    { duration: "1 Hour", price: "2.000 DKK" },
    { duration: "2 Hours", price: "3.500 DKK" },
    { duration: "Overnight", price: "8.000 DKK" },
    { duration: "Weekend", price: "20.000 DKK" },
  ],
  services: [
    "GFE",
    "Dinner Date",
    "Travel Companion",
    "Overnight",
    "BDSM",
    "Massage",
    "Role Play",
    "Striptease",
  ],
  contact: {
    phone: "+45 XX XX XX XX",
    whatsapp: "+45 XX XX XX XX",
    telegram: "@sofiacph",
    email: "sofia@redlightad.com",
  },
};
